# -*- coding: utf-8 -*-
"""my_app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HDLHruRStD_JjQHCyJd4O3x28gqNYqfN
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go
import seaborn as sns

data = pd.read_csv('/open_meteo.csv', sep=',', engine = 'python')

from google.colab import drive
drive.mount('/content/drive')

data.tail()

data.info()

dict_location = {0:'Київ', 1:'Вінниця',2:'Дніпро',3:'Львів',4:'Харків',5:'Одеса',6:'Миколаїв',7:'Запоріжжя',8:'Кропивницький',9:'Чернівці',10:'Суми',11:'Полтава',12:'Тернопіль',13:'Ужгород',14:'Хмельницький',15:'Черкаси',16:'Рівне',17:'Івано-Франківськ',18:'Чернігів',19:'Херсон',20:'Луцьк'}
data['location_id']= data['location_id'].map(dict_location)

data['location_id'].unique()

data['time'] = pd.to_datetime(data['time'])

data.info()

data.describe().round(1)

data.isnull().sum()

fig = px.line(data, x = 'time', y = 'temperature_2m (°C)', color = 'location_id', title = 'Температура в часі для різних локацій')
fig.update_layout(xaxis_title = 'Час', yaxis_title= 'Температура')
fig.show()

fig = px.density_heatmap(
    data,
    x='time',
    y='location_id',
    z='temperature_2m (°C)',
    color_continuous_scale='RdBu_r',
    title='Температура: час × локація'
)

fig.show()

fig = px.scatter(data, x = 'time', y = 'temperature_2m (°C)', color='location_id', opacity=0.3)
fig.update_layout(xaxis_title= 'Час доби', yaxis_title='Температура')
fig.show()